# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mugikuru < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktamamu/mugikuru/releases/download/v0.2.0/mugikuru_Darwin_x86_64.tar.gz"
      sha256 "946b615b7eeeec7e4beef2a916fa7b8708165e79152a1dc6165e2b2e22a1ebc3"

      def install
        bin.install "mugikuru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktamamu/mugikuru/releases/download/v0.2.0/mugikuru_Darwin_arm64.tar.gz"
      sha256 "8045650ad33d8c8eb160325d40bc3e6a72f8abc0e63957c0c0acefc191e9961d"

      def install
        bin.install "mugikuru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/mugikuru/releases/download/v0.2.0/mugikuru_Linux_x86_64.tar.gz"
      sha256 "22d9049e744f92f6d9a24540094847b0e7931ad001dd2dc0e5ba418ee5967668"
      def install
        bin.install "mugikuru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/mugikuru/releases/download/v0.2.0/mugikuru_Linux_arm64.tar.gz"
      sha256 "b1b33fba14cad0e901e71c850f21fe2dffd0c7abf755eff1b935318987ec6711"
      def install
        bin.install "mugikuru"
      end
    end
  end
end
