# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mugikuru < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktamamu/mugikuru/releases/download/v0.1.6/mugikuru_Darwin_x86_64.tar.gz"
      sha256 "e7ca411719e7cff205288247d93cf8981c781dfcc054d254633245682068ab4e"

      def install
        bin.install "mugikuru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktamamu/mugikuru/releases/download/v0.1.6/mugikuru_Darwin_arm64.tar.gz"
      sha256 "6129bbeb6a1afe07eca6824f16cef48390f6480aa3e4f96dddaeeb979aa8139c"

      def install
        bin.install "mugikuru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ktamamu/mugikuru/releases/download/v0.1.6/mugikuru_Linux_x86_64.tar.gz"
        sha256 "935215ae8d32f9e9ee43a10786637cd85ec7af741c370fea02d703023dd6e203"

        def install
          bin.install "mugikuru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ktamamu/mugikuru/releases/download/v0.1.6/mugikuru_Linux_arm64.tar.gz"
        sha256 "563545922b25769023b4bd0a9a22b848255cd5519425bfa0f34e4db09698ee75"

        def install
          bin.install "mugikuru"
        end
      end
    end
  end
end
