# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sglobal < Formula
  desc "AWS Security Group Global Access Scanner"
  homepage "https://github.com/ktamamu/sglobal"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "d5bfd57ef27096bbb60595229063d64a655bb601a3d6cc976e2370e9d2c5a498"

      def install
        bin.install "sglobal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Darwin_arm64.tar.gz"
      sha256 "b79b28e327265db8539e726b63da9dd1184208b3b778e31391b0a123c1f742dd"

      def install
        bin.install "sglobal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Linux_x86_64.tar.gz"
      sha256 "e9c47df785d9589796fb617ab56bdcdce88183378f196b0b79547928852b0f04"
      def install
        bin.install "sglobal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Linux_arm64.tar.gz"
      sha256 "d471f2cdcaef46db34f7e5b49792ba46089b699cfc858dec44e7ebebbab6ed2e"
      def install
        bin.install "sglobal"
      end
    end
  end

  test do
    assert_match "AWS Security Group Global Access Scanner", shell_output("#{bin}/sglobal --help")
  end
end
