# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sglobal < Formula
  desc "AWS Security Group Global Access Scanner"
  homepage "https://github.com/ktamamu/sglobal"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "dcc2f168efc577b8383d6f2007314b688d86e710e442af7cfb80ee3bbb5ebc0d"

      def install
        bin.install "sglobal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Darwin_arm64.tar.gz"
      sha256 "3c7c9789d037162ff60bef7ab9aa0dbddd596f4d47525b5686f170ff91e60303"

      def install
        bin.install "sglobal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Linux_x86_64.tar.gz"
      sha256 "84a4ed8088a42788bf716fcf7982659de762de221b058be363e0b43c173e2595"
      def install
        bin.install "sglobal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.1.2/sglobal_0.1.2_Linux_arm64.tar.gz"
      sha256 "ebf446e8a3bd5dc11ad6b3177931f9928b403e72a982ff514717754685ef7c68"
      def install
        bin.install "sglobal"
      end
    end
  end

  test do
    assert_match "AWS Security Group Global Access Scanner", shell_output("#{bin}/sglobal --help")
  end
end
