# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sglobal < Formula
  desc "AWS Security Group Global Access Scanner"
  homepage "https://github.com/ktamamu/sglobal"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.2.1/sglobal_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "cf8778fb278405f37dd324b3d4f872392c53fa3d2b9187deb78c48050e21b3b8"

      define_method(:install) do
        bin.install "sglobal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.2.1/sglobal_0.2.1_Darwin_arm64.tar.gz"
      sha256 "37cd291b1b3d2af7ed7285bee866db0e5efb2db67e45fa9ecb9326739cd9eaae"

      define_method(:install) do
        bin.install "sglobal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.2.1/sglobal_0.2.1_Linux_x86_64.tar.gz"
      sha256 "c2be019e012c919be1deb96acd7a7a01fdcb3837d7d3ba7b8188e0bb89aaf9cf"
      define_method(:install) do
        bin.install "sglobal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktamamu/sglobal/releases/download/v0.2.1/sglobal_0.2.1_Linux_arm64.tar.gz"
      sha256 "f54e3a4657ae5ac4bc143da25c2a8c9db77386844ab25ddb32e935d3a8be13e7"
      define_method(:install) do
        bin.install "sglobal"
      end
    end
  end

  test do
    assert_match "AWS Security Group Global Access Scanner", shell_output("#{bin}/sglobal --help")
  end
end
